spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/spring_security_oauth2?useSSL=false&serverTimezone=GMT&useLegacyDatetimeCode=false"
    username: "root"
    password: "${MY_PASSWORD}"

  jpa:
    show-sql: true
    open-in-view: true
#    properties:
#      hibernate:
#        dialect: "org.hibernate.dialect.MySQLDialect"
#        format_sql: "true"
    hibernate:
      ddl-auto: "update"
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
