spring:
  output.ansi.enabled: always
openapi:
  service:
    title: "API Spring Security Service Document"
    version: "v1.0.0"
    description: "Api security service for {profile}"
    license:
      name: "API License"
      identifier: "MIT"
      url: "https://{profile}-server:8080/api-docs"
logging:
  level:
    root: INFO
    org.springframework.web: INFO
  pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m %X{Remote_Address} %clr(%n%wEx){red}"